// @vitest-environment jsdom
import React, { act } from 'react';
import { Simulate } from 'react-dom/test-utils';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import NavigationBall, { DraggableNavigationBall } from '../components/os/NavigationBall';
import NavigationBallSettings from '../components/settings/NavigationBallSettings';
import { NAVIGATION_SLOT_APPS, resetNavigationBallPosition, setNavigationBallEnabled, setNavigationBallSlot } from './navigationBall';
import { AppID } from '../types';
import { requestSettingsFocus, useSettingsFocus } from './settingsNavigation';
const state = vi.hoisted(() => ({ isLocked: false, handleBack: vi.fn(), closeApp: vi.fn(), openApp: vi.fn() }));
vi.mock('../context/OSContext', () => ({ useOS: () => state }));
vi.mock('./iosStandalone', () => ({ isIOSStandaloneWebApp: () => false, readSafeAreaInsets: () => ({ top: 20, bottom: 24 }) }));
let root: Root, host: HTMLDivElement;
let resize: () => void;
beforeEach(() => {
  (globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;
  localStorage.clear(); setNavigationBallEnabled(false); state.isLocked = false; vi.clearAllMocks();
  window.dispatchEvent(new StorageEvent('storage', { key: null }));
  host = document.createElement('div'); document.body.append(host); root = createRoot(host);
  vi.spyOn(host, 'getBoundingClientRect').mockReturnValue({ width: 320, height: 600, left: 0, top: 0 } as DOMRect);
  vi.stubGlobal('ResizeObserver', class { constructor(callback: () => void) { resize = callback; } observe() {} disconnect() {} });
});
afterEach(async () => { await act(async () => root.unmount()); host.remove(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
const render = async (element: React.ReactNode) => act(async () => root.render(element));
const click = async (button: Element) => act(async () => (button as HTMLElement).click());
it('starts disabled, enables from settings immediately, separates back/home and hides on lock/disable', async () => {
  await render(React.createElement(React.Fragment, null, React.createElement(NavigationBallSettings), React.createElement(NavigationBall)));
  expect(host.querySelector('.navigation-ball')).toBeNull();
  const sectionToggle = [...host.querySelectorAll('button')].find(button => button.textContent === '悬浮球设置')!;
  expect(sectionToggle.getAttribute('aria-expanded')).toBe('false'); expect(host.querySelector('[role=switch]')).toBeNull();
  await click(sectionToggle);
  const toggle = host.querySelector('[role=switch]') as HTMLButtonElement;
  await click(toggle); expect(toggle.getAttribute('aria-checked')).toBe('true'); expect(localStorage.getItem('sully_navigation_ball_enabled_v1')).toBe('1');
  await click(sectionToggle); expect(host.querySelector('[role=switch]')).toBeNull(); expect(host.querySelector('.navigation-ball')).not.toBeNull();
  const scroll = vi.fn(); Object.defineProperty(host.querySelector('section'), 'scrollIntoView', { value: scroll });
  await act(async () => requestSettingsFocus('navigation'));
  expect(sectionToggle.getAttribute('aria-expanded')).toBe('true'); expect(scroll).toHaveBeenCalledOnce();
  await click(host.querySelector('.navigation-ball-toggle')!);
  await click(host.querySelector('[aria-label="返回上一级"]')!);
  expect(state.handleBack).toHaveBeenCalledOnce(); expect(state.closeApp).not.toHaveBeenCalled();
  await click(host.querySelector('.navigation-ball-toggle')!);
  await click(host.querySelector('[aria-label="回到桌面"]')!);
  expect(state.closeApp).toHaveBeenCalledOnce();
  state.isLocked = true; await render(React.createElement(NavigationBall)); expect(host.querySelector('.navigation-ball')).toBeNull();
  state.isLocked = false; await act(async()=>setNavigationBallEnabled(false)); await render(React.createElement(NavigationBall)); expect(host.querySelector('.navigation-ball')).toBeNull();
});
it('clamps dragging and restored position to safe bounds, saves only on release and does not open on drag/cancel', async () => {
  localStorage.setItem('sully_navigation_ball_position_v1', JSON.stringify({ x: 900, y: 900 }));
  await render(React.createElement(DraggableNavigationBall, { onBack: vi.fn(), onHome: vi.fn(), onApi: vi.fn(), onShortcut: vi.fn(), onConfigure: vi.fn() }));
  const bubble = host.querySelector('.navigation-ball-toggle') as HTMLButtonElement, wrapper = host.querySelector('.navigation-ball') as HTMLElement;
  expect(wrapper.style.left).toBe('268px'); expect(wrapper.style.top).toBe('524px');
  const writes = vi.spyOn(Storage.prototype, 'setItem');
  await act(async () => {
    Simulate.pointerDown(bubble, { pointerId: 1, button: 0, clientX: 280, clientY: 540 } as any);
    Simulate.pointerMove(bubble, { pointerId: 1, clientX: -500, clientY: -500 } as any);
  });
  expect(wrapper.style.left).toBe('8px'); expect(wrapper.style.top).toBe('28px'); expect(writes).not.toHaveBeenCalled();
  await act(async () => { Simulate.pointerUp(bubble, { pointerId: 1 } as any); bubble.dispatchEvent(new MouseEvent('click', { bubbles: true, detail: 1 })); });
  expect(JSON.parse(localStorage.getItem('sully_navigation_ball_position_v1')!)).toEqual({x:8,y:28});
  expect(writes).toHaveBeenCalledOnce(); expect(bubble.getAttribute('aria-expanded')).toBe('false');
  await act(async () => { Simulate.pointerDown(bubble, { pointerId: 2, button: 0, clientX: 20, clientY: 40 } as any); Simulate.pointerCancel(bubble, { pointerId: 2 } as any); });
  expect(bubble.getAttribute('aria-expanded')).toBe('false');
  vi.mocked(host.getBoundingClientRect).mockReturnValue({ width: 180, height: 260, left: 0, top: 0 } as DOMRect);
  await act(async () => resize()); expect(parseInt(wrapper.style.top)).toBeLessThanOrEqual(184);
  await click(bubble);
  const panel = host.querySelector('.navigation-ball-panel') as HTMLElement;
  expect(panel.style.maxHeight).toBe('192px');
  expect(parseFloat(wrapper.style.left) + parseFloat(panel.style.left)).toBe(12);
  expect(parseFloat(wrapper.style.top) + parseFloat(panel.style.top)).toBe(32);
  expect(panel.style.width).toBe('156px');
  vi.mocked(host.getBoundingClientRect).mockReturnValue({ width: 180, height: 180, left: 0, top: 0 } as DOMRect);
  await act(async () => resize()); expect(panel.style.maxHeight).toBe('112px'); expect(panel.style.overflowY).toBe('auto');
});
it('opens API directly, migrates and persists four slots including Settings and rejects hidden/invalid entries', async () => {
  const apiFocus = vi.fn(), navigationFocus = vi.fn();
  function FocusTargets() {
    useSettingsFocus('api', apiFocus); useSettingsFocus('navigation', navigationFocus); return null;
  }
  await act(async () => setNavigationBallEnabled(true));
  await render(React.createElement(React.Fragment, null, React.createElement(NavigationBallSettings), React.createElement(FocusTargets), React.createElement(NavigationBall)));
  await click([...host.querySelectorAll('button')].find(button => button.textContent === '悬浮球设置')!);
  await act(async () => {
    setNavigationBallSlot(0, { appId: AppID.Chat }); setNavigationBallSlot(1, { appId: AppID.Room, roomTab: 'room' });
    setNavigationBallSlot(2, { appId: AppID.Appearance }); setNavigationBallSlot(3, { appId: AppID.Settings });
  });
  expect(JSON.parse(localStorage.getItem('sully_navigation_ball_slots_v1')!)).toEqual([{ appId: AppID.Chat }, { appId: AppID.Room, roomTab: 'room' }, { appId: AppID.Appearance }, { appId: AppID.Settings }]);
  const action = async (label: string) => { await click(host.querySelector('.navigation-ball-toggle')!); await click(host.querySelector(`[aria-label="${label}"]`)!); };
  await action('打开Message'); expect(state.openApp).toHaveBeenLastCalledWith(AppID.Chat);
  await click(host.querySelector('.navigation-ball-toggle')!);
  await click([...host.querySelectorAll('.navigation-ball-panel button')].find(button => button.textContent === 'API 配置')!);
  expect(state.openApp).toHaveBeenLastCalledWith(AppID.Settings); expect(apiFocus).toHaveBeenCalledOnce();
  await action('打开设置');
  expect(state.openApp).toHaveBeenLastCalledWith(AppID.Settings); expect(apiFocus).toHaveBeenCalledOnce();
  await act(async () => setNavigationBallSlot(2, null)); await action('设置 App 槽位 3'); expect(navigationFocus).toHaveBeenCalledOnce();
  expect(NAVIGATION_SLOT_APPS.some(app => app.id === AppID.CharCreatorDev || app.id === AppID.ThemeMaker || app.id === AppID.WorldHome)).toBe(false);
  localStorage.setItem('sully_navigation_ball_slots_v1', JSON.stringify([AppID.Room, 'invalid', AppID.CharCreatorDev]));
  await act(async () => window.dispatchEvent(new StorageEvent('storage', { key: 'sully_navigation_ball_slots_v1' })));
  expect(host.querySelector('[aria-label="配置悬浮球槽位 1"]')?.textContent).toContain('小小窝');
  expect(host.querySelector('[aria-label="配置悬浮球槽位 2"]')?.textContent).toContain('未设置');
  expect(host.querySelectorAll('[aria-label^="配置悬浮球槽位"]').length).toBe(4);
  const reads = vi.spyOn(Storage.prototype, 'getItem');
  await render(React.createElement(NavigationBall));
  expect(reads).not.toHaveBeenCalledWith('sully_navigation_ball_slots_v1');
  reads.mockClear(); await render(React.createElement(NavigationBall)); expect(reads).not.toHaveBeenCalled();
});
it('rescues a displaced ball immediately, closes its menu and preserves enabled state and shortcuts', async () => {
  setNavigationBallEnabled(true); setNavigationBallSlot(0, { appId: AppID.Chat, characterId: 'sully' });
  localStorage.setItem('sully_navigation_ball_position_v1', JSON.stringify({ x: 8, y: 28 }));
  await render(React.createElement(React.Fragment, null, React.createElement(NavigationBallSettings), React.createElement(NavigationBall)));
  const wrapper = host.querySelector('.navigation-ball') as HTMLElement;
  const slotsBefore = localStorage.getItem('sully_navigation_ball_slots_v1');
  await click(host.querySelector('.navigation-ball-toggle')!); expect(host.querySelector('.navigation-ball-panel')).not.toBeNull();
  await click([...host.querySelectorAll('button')].find(button => button.textContent === '悬浮球设置')!);
  await click([...host.querySelectorAll('button')].find(button => button.textContent === '悬浮球复位抢救')!);
  expect(wrapper.style.left).toBe('264px'); expect(wrapper.style.top).toBe('460px');
  expect(host.querySelector('.navigation-ball-panel')).toBeNull(); expect(localStorage.getItem('sully_navigation_ball_position_v1')).toBeNull();
  expect(localStorage.getItem('sully_navigation_ball_enabled_v1')).toBe('1'); expect(localStorage.getItem('sully_navigation_ball_slots_v1')).toBe(slotsBefore);
  const remove = vi.spyOn(Storage.prototype, 'removeItem').mockImplementation(() => { throw new Error('storage unavailable'); });
  await act(async () => resetNavigationBallPosition()); expect(wrapper.style.left).toBe('264px');
  remove.mockRestore();
  await act(async () => setNavigationBallEnabled(false));
  await click([...host.querySelectorAll('button')].find(button => button.textContent === '悬浮球复位抢救')!);
  expect(host.querySelector('.navigation-ball')).toBeNull(); expect(localStorage.getItem('sully_navigation_ball_enabled_v1')).toBe('0');
});
